### ISSUE TITLE
How to not rely on  StrictHostKeyChecking accept-new ?

### ISSUE THREAD

**Issue by emidevops** [outscale/osc-k8s-rke-cluster#30]
Is there a way to set the host key using Outscale provider (and generate the corresponding known_hosts file) instead of relying StrictHostKeyChecking accept-new ?

https://github.com/outscale/osc-k8s-rke-cluster/blob/master/ssh_config.tf

**Comment by jerome-jutteau** [comment]
Hi @emidevops ,

I agree that specifying pre-computed ssh keys for each node would be better.

Note for dev: use [cloudinit's ssh_keys](https://cloudinit.readthedocs.io/en/0.7.7/topics/examples.html?highlight=string#configure-instances-ssh-keys).
